### PR TITLE
Added Facebook link and fixed some typos.

### PR DESCRIPTION
**Pull request by PabloCarmona**
Hello, this is my first contribution to this project I get interested in push.
I hope all goes good with my implementation.
If I make mistakes on something let me now I'm here to help and learn!

Thank you!

### CODE REVIEW

**Comment by PabloCarmona** [comment]
I realized that we can put the link also in the blog page. You think is good idea?

**Comment by tiltec** [comment]
Hi Pablo, great start, nice to have you here! Maybe the topbar is getting too full, what do you think about extending the footer? Otherwise it's perfect!

I guess we can have it on the blog as well - do you know how to modify our blog (based on Jekyll)?

**Comment by PabloCarmona** [comment]
I can't see any footer in the page. If you want I can create one following the styling rules and for the blog I haven't any experience in work with Jekyll but I can give it a shot and inform you with the progress.

Thanks for bring me the oportunity to join this cool project!

**Comment by tiltec** [comment]
True, there is no footer on the landing page and on the splash pages. But there is one when you are on the "main" view (e.g. viewing a group or a store).

(Sorry for the delay, still travelling around!)

**Comment by tiltec** [comment]
More detail: the footer is [here](https://github.com/yunity/foodsaving-frontend/blob/master/client/app/layouts/main.html#L10)
You can simply extend it for now - later on, we should refactor it into a component to reuse it on the login page etc..

**Comment by PabloCarmona** [comment]
Added the link in the footer. Sorry for the delay and thanks for help! 😄

**Comment by tiltec** [comment]
Merged!
Our translations are handled in transifex, I fixed the spelling here instead: https://www.transifex.com/yunity-1/foodsaving-tool/translate/#es/frontend/102480249

**Pull request merged**
