### PR TITLE
WIP: Conversations

### PR DESCRIPTION
**Pull request by alangecker**
### known issues: 
- [ ] Conversation does not get loaded: controller can not see the correct id on constructing since i merged the master locally
- [ ] Conversation list get reloaded on each thread change. how can we avoid that?
- [ ] date separator should only get showed when the date changes
- [X] and a lot of lint complaints^^

### ToDo's until merging
- [ ] tests
- [ ] new conversation
- [ ] send message
- [ ] i18n 
- [ ] use `$q` instead of native `Promise` with `$scope.$apply()`

further tasks under #151 

screenshot_2016-12-09_03-16-33

### CODE REVIEW

**Comment by tiltec** [comment]
I would have a look over the code in the next days, if you feel like it. Tell me when you are ready ;)

**Comment by D0nPiano** [comment]
> Conversation list get reloaded on each thread change. how can we avoid that?

Maybe like the nested views in storeMultiView?
So that `conversations` is the parent view
```
.state("conversation", {
      parent: "main",
      url: "/conversation/",                    // Removed ":id"
      component: "conversations"
}
```
of conversations/conversation, that has its own route:
```
.state("conversation.conversations", {
      url: "/conversation/:id",
      component: "conversation",
}
```

and instead of having the `<conversation></conversation>` component, you just include a `<ui-view>` element

**Comment by D0nPiano** [comment]
> date separator should only get showed when the date changes

I actually had the exact same problem in the `_pickupList ` component. It was a little tricky, and in the end I just had a [groupByDate function](https://github.com/yunity/foodsaving-frontend/blob/conversations/client/app/components/_pickupList/pickupList.controller.js#L78) that get's called whenever the list is updated. I think the problem is quite similar here.

**Comment by alangecker** [comment]
i'm gonna close this for now, because it has a pretty low priority and going be remade differently anyway.

**Pull request closed without merging**
