### PR TITLE
Landing page & storeMap

### PR DESCRIPTION
**Pull request by D0nPiano**
## Landingpage
...where a store map and a tool description can be shown.
Currently looks like this:

screenshot from 2017-02-28 00-19-41
screenshot from 2017-02-27 23-56-29

Usesful for showing public map of all groups #176, and possibly linking to:
- Team Page #325 
- Introduction page #326 
- Our Blog

### ToDos
- [x] Test
- [x] Translate
- [x] make more mobile friendly
- [x] set better inital position of map
- [x] make map refresh nicer (had to include some ugly code because map was grey when I first loaded the page)
- [x] replace "statistics" with "blog" for now
#### Maybe:
- [ ] include animated scroll to map

### CODE REVIEW

**Comment by tiltec** [comment]
Wow, amazing work! I can have a look at the map refresh later.

**Comment by tiltec** [comment]
I disabled scroll zoom, it doesn't behave nice on scrollable pages.
We could put a button there to open the page fullscreen with enable scroll zoom.

**Comment by djahnie** [comment]
Oooh that looks great! Thanks a bunch @D0nPiano! 😃 
And with this layout it's gonna be easy to add a button that links to all the written material we already have on the wiki! Although it'd be much nicer to have the content _really_ integrated in the page and not only link to confluence... (I know that's something else and here it's actually digressing, but it just came to my mind so I wanted to share it... 😉)

**Comment by D0nPiano** [comment]
Thanks @tiltec for the tests & max zoom! And thanks to you both for review 🙂  And linking our confluence wiki somewhere also sounds like a good idea.

I just added the font 'Cabin Sketch' that's also used on yuca.yunity.org today.
screenshot from 2017-02-28 20-44-13

Also, the map now displays watercolored tiles. What do you think? Cool? Or too much?
screenshot from 2017-02-28 20-44-34

Other than that it should be mergeable now :)

**Pull request merged**
