### PR TITLE
refactor: Create service for determining screen size

### PR DESCRIPTION
**Pull request by azzang**
The service provides a function that wraps $mdMedia (an AngularJS Material service) and returns a boolean indicating whether a screen is wider than 960px.

The service can be extended by adding similar functions to test for other breakpoints.

Resolves: #465

### CODE REVIEW

**Comment by tiltec** [comment]
Looks good to me! Would you be up for replacing calls to `$mdMedia` in our codebase with your brand new service?

**Comment by azzang** [comment]
Great! I'm totally up for replacing the calls. One quick question:

Do you have any preference as far as how the service should be exposed (on
the controller, scope, rootScope, ...)? I'm leaning toward the controller,
with calls from templates that look like:
$ctrl.ScreenSize.isMediumOrLarger(). I think this would be the cleanest
approach, in terms of replacing the calls.

Let me know :)

Jazz

**Comment by tiltec** [comment]
> $ctrl.ScreenSize.isMediumOrLarger()

That seems the best choice to me, too.

Though maybe it makes sense to shorten `isMediumOrLarger()` to something like `gtSm()`?

**Comment by azzang** [comment]
Done.

I added an "is" to your function name (i.e. isGtSm instead of gtSm) since
it returns a boolean. Also, I realized that $mdMedia was being passed
"gt-xs" in a few places, so I added another function (isGtXs) to the
service.

Not sure if I got everything, so any feedback would be great!

**Comment by tiltec** [comment]
Thanks @azzang, great work! (also for the whitespace fixes 👍 )
I will merge it to master now, the changes should be live soon on dev.foodsaving.world

**Comment by azzang** [comment]
Thanks Tilmann. Happy to help!

**Pull request merged**
